config/routes.rb
Rails.application.routes.draw do
  
  resources :contracts
  resources :contracts
  resources :searches
  resources :users
  resources :profiles
  resources :subjects
  get 'home/index'

  
  root :to => "home#index"

devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

devise_scope :user do
  get "sign_in", to: "devise/sessions#new"
end

end

app/models/contract.rb
class Contract < ActiveRecord::Base
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy]

  # GET /contracts
  # GET /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1
  # GET /contracts/1.json
  def show
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts
  # POST /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to @contract, notice: 'Contract was successfully created.' }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1
  # PATCH/PUT /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to @contract, notice: 'Contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.json
  def destroy
    @contract.destroy
    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contract_params
      params.require(:contract).permit(:date_from, :date_to, :description)
    end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.erb
<%= simple_form_for(@contract) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :date_from %>
    <%= f.input :date_to %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing Contract</h1>

<%= render 'form' %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contracts</h1>

<table>
  <thead>
    <tr>
      <th>Date from</th>
      <th>Date to</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td><%= contract.date_from %></td>
        <td><%= contract.date_to %></td>
        <td><%= contract.description %></td>
        <td><%= link_to 'Show', contract %></td>
         <%if user_signed_in? && current_user.is_landlord?%>
        <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
        <td><%= link_to 'Destroy', contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 <%if user_signed_in? && current_user.is_landlord?%>
<%= link_to 'New Contract', new_contract_path %>
<%end%>

app/views/contracts/new.html.erb
<h1>New Contract</h1>

<%= render 'form' %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date from:</strong>
  <%= @contract.date_from %>
</p>

<p>
  <strong>Date to:</strong>
  <%= @contract.date_to %>
</p>

<p>
  <strong>Description:</strong>
  <%= @contract.description %>
</p>
 <%if user_signed_in? && current_user.is_landlord?%>
<%= link_to 'Edit', edit_contract_path(@contract) %> |
<%end%>
<%= link_to 'Back', contracts_path %>