config/routes.rb
Rails.application.routes.draw do
  
  resources :contracts
  resources :contracts
  resources :searches
  resources :users
  resources :profiles
  resources :subjects
  get 'home/index'

  
  root :to => "home#index"

devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

devise_scope :user do
  get "sign_in", to: "devise/sessions#new"
end

end

app/models/subject.rb
class Subject < ActiveRecord::Base

#attr_accessible :image, :remote_image_url
mount_uploader :image, ImageUploader
self.inheritance_column = nil
has_many :images, dependent: :destroy

 #has_many :post_attachments
 #accepts_nested_attributes_for :post_attachments, :images
 accepts_nested_attributes_for :images

 def user_params
      params.require(:subject).permit(:image, :remote_image_url)
    end


def self.search(search)
  if search
    self.where("name like ?", "%#{search}%")
  else
    self.all
  end
end

    
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    #@subjects = Subject.all
    @subjects = Subject.search(params[:search])

  end


  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new

    5.times do 
      @subject.images.build

    end

  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :type, :description, :image, :remote_image_url, images_attributes: [:image, :id])
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for @subject, :html => {:multipart => true} do |f| %>

  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>



   <div class="field">
    <%= f.label :type %><br />
    <%= f.select :type, options_for_select(["Movitost","Nemovitost", "Ostatní"])%>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

 <div class="field">
    <%= f.fields_for :images, @subject.images do |i| %>
    <%=i.file_field :image %>
    <%end%>
  </div>

  

 <div class="field">
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.type %></td>
        <td><%= subject.description %></td>
        <td><%= link_to 'Show', subject %></td>

         <%if user_signed_in? && current_user.is_landlord?%>

        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>


<%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <%if user_signed_in? && current_user.is_landlord?%>

<%= link_to 'New Subject', new_subject_path %>
<%end%>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @subject.type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @subject.description %>
</p>


<%@subject.images.each do |im|%>
<%=image_tag im.image.url(:small)%>
<%end%>

<%= image_tag @subject.image_url(:small) if @subject.image? %>


 <%if user_signed_in? && current_user.is_landlord?%>
<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%end%>

<%= link_to 'Back', subjects_path %>